version: '3.8'

services:
  gpttopdf:
    build: .
    ports:
      - "127.0.0.1:5000:5000"  # Nur lokal erreichbar
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Add shared memory for Chromium
    shm_size: 2gb
