services:
  - type: web
    name: gpttopdf
    env: python
    buildCommand: pip install -r requirements.txt && chmod +x bin/post_compile && bin/post_compile
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright
